### ISSUE TITLE
Implement specs for transformation methods

### ISSUE THREAD

**Issue by fdupont-redhat** [ManageIQ/manageiq-content#360]
Over time, the Transformation namespace has been populated to implement new features, but no spec has been provided, increasing the overall technical debt of the project. This issue tracks the implementation of specs for this namespace, in order to reach full coverage:

- [x] [[PR#441]](https://github.com/ManageIQ/manageiq-content/pull/441) /Transformation/Common.class/__methods__/acquiretransformationhost.rb
- [x] [[PR#408]](https://github.com/ManageIQ/manageiq-content/pull/408) /Transformation/Common.class/__methods__/assesstransformation.rb
- [X] [[PR#385]](https://github.com/ManageIQ/manageiq-content/pull/385) /Transformation/Infrastructure/VM/Common.class/__methods__/restorevmattributes.rb
- [x] [[PR#391]](https://github.com/ManageIQ/manageiq-content/pull/391) [[PR#410]](https://github.com/ManageIQ/manageiq-content/pull/410) /Transformation/Infrastructure/VM/Common.class/__methods__/utils.rb
- [x] [[PR#441]](https://github.com/ManageIQ/manageiq-content/pull/441) /Transformation/Infrastructure/VM/rhevm.class/__methods__/checkpoweredon.rb
- [x] [[PR#399]](https://github.com/ManageIQ/manageiq-content/pull/399) /Transformation/Infrastructure/VM/Common.class/__methods__/checkvmininventory.rb
- [x] [[PR#421]](https://github.com/ManageIQ/manageiq-content/pull/421) /Transformation/TransformationHosts/Common.class/__methods__/utils.rb
- [x] [[PR#433]](https://github.com/ManageIQ/manageiq-content/pull/433) /Transformation/TransformationHosts/Common.class/__methods__/killvirtv2v.rb
- [x] [[PR#421]](https://github.com/ManageIQ/manageiq-content/pull/421) /Transformation/TransformationHosts/ovirt_host.class/__methods__/utils.rb

**Previously specified methods that have been removed from the repo:**
/Transformation/Infrastructure/VM/Common.class/__methods__/poweroff.rb
/Transformation/Infrastructure/VM/Common.class/__methods__/poweron.rb
/Transformation/Infrastructure/VM/vmwarews.class/__methods__/collapsesnapshots.rb
/Transformation/Infrastructure/VM/vmwarews.class/__methods__/setmigrated.rb
/Transformation/Infrastructure/VM/vmwarews.class/__methods__/utils.rb
/Transformation/TransformationHosts/ovirt_host.class/__methods__/rolecheck.rb
/Transformation/TransformationHosts/ovirt_host.class/__methods__/roledisable.rb
/Transformation/TransformationHosts/ovirt_host.class/__methods__/roleenable.rb
/Transformation/TransformationHosts/ovirt_host.class/__methods__/tagasdisabled.rb
/Transformation/TransformationHosts/ovirt_host.class/__methods__/tagasenabled.rb
/Transformation/TransformationHosts/StateMachines/TransformationHostRole.class/__methods__/update_status.rb

Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1600870

**Comment by fdupont-redhat** [comment]
@miq-bot add-label enhancement

**Comment by fdupont-redhat** [comment]
@miq-bot add-label gaprindashvili/yes
@miq-bot add-label transformation

**Comment by gmcculloug** [comment]
@fdupont-redhat I reviewed the current state of the Transformation namespace since most of the logic has moved out the the content repo.  

We are down to three of the Approval methods in [ManageIQ/Transformation/StateMachines/TransformationPlanRequestApproval.class/__methods__](https://github.com/ManageIQ/manageiq-content/tree/master/content/automate/ManageIQ/Transformation/StateMachines/TransformationPlanRequestApproval.class/__methods__)

I will add those methods to the generic refactoring issue (https://github.com/ManageIQ/manageiq-content/issues/8) and close this one out.  Let me know if you have any questions.

**Comment by fdupont-redhat** [comment]
Thanks @gmcculloug
